#!/bin/bash
IMAGE_NAME='robot-docker'
VOLUME_NAME='robot-docker-volume'

sudo docker build -t $IMAGE_NAME .
build=$!
wait $build
sudo docker run -d --name $VOLUME_NAME -v $(pwd):/robot --shm-size=1gb $IMAGE_NAME:latest
volume=$!
wait $volume
