#!/bin/bash
IMAGE_NAME='robot-docker'

sudo docker ps -a | awk '{ print $1,$2 }' | grep $IMAGE_NAME:latest | awk '{print $1}' | xargs -I {} sudo docker stop {}
stop=$!
wait $stop
sudo docker ps -a | awk '{ print $1,$2 }' | grep $IMAGE_NAME:latest | awk '{print $1}' | xargs -I {} sudo docker rm {}
remove=$!
wait $remove
sudo docker rmi $IMAGE_NAME
delete=$!
wait $delete
